# Generated by Django 3.2.13 on 2022-07-07 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosaic',
            name='finished',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
